// The architectural invariants, checked rather than trusted.
//
// A layering rule that lives only in a document is a rule that lasts until the
// first hurried afternoon. These read the source and fail the suite.
//
// From the locked contract section 7:
//   A1  components/ may import design/ and l10n/; design/ imports nothing
//       from components/
//   A2  no raw Color, font size or spacing literal outside design/
//   A3  no user-visible string literal outside l10n/   (scan_hardcoded.py)
//   A4  nothing imports a database, network or storage package
//   A5  no business-rule constant anywhere            (scan_hardcoded.py)

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

Iterable<File> _dartFiles(String dir) => Directory(dir)
    .listSync(recursive: true)
    .whereType<File>()
    .where((f) => f.path.endsWith('.dart'))
    // Generated by gen-l10n from the .arb catalogues.
    .where((f) => !f.path.contains('app_localizations'));

void main() {
  group('layering', () {
    test('design/ does not import components/ or gallery/', () {
      for (final file in _dartFiles('lib/design')) {
        final source = file.readAsStringSync();
        expect(
          source.contains("import '../../components/") ||
              source.contains("import '../components/") ||
              source.contains("import '../gallery/") ||
              source.contains('package:dhaaga/components/') ||
              source.contains('package:dhaaga/gallery/'),
          isFalse,
          reason: '${file.path} imports upward. The token layer must not know '
              'what is drawn with it, or a palette change stops being a '
              'one-file edit.',
        );
      }
    });

    test('components/ does not import gallery/', () {
      for (final file in _dartFiles('lib/components')) {
        expect(
          file.readAsStringSync().contains('gallery/'),
          isFalse,
          reason: '${file.path} imports the gallery. The gallery is a test '
              'harness; nothing may depend on it.',
        );
      }
    });
  });

  group('no data access anywhere in the client foundation', () {
    // WP-9 renders inputs. Tenancy, identity, authorization and business rules
    // are the database's, and a client that starts fetching is a client that
    // will eventually start deciding (ADR-0012).
    const forbidden = <String>[
      'package:http/',
      'package:dio/',
      'package:supabase',
      'package:postgrest',
      'package:sqflite',
      'package:drift/',
      'package:isar/',
      'package:hive',
      'package:shared_preferences',
      'dart:io',
      'dart:html',
    ];

    test('lib/ imports no network, database or storage package', () {
      for (final file in _dartFiles('lib')) {
        final source = file.readAsStringSync();
        for (final package in forbidden) {
          expect(
            source.contains("import '$package"),
            isFalse,
            reason: '${file.path} imports $package. WP-9 has no data layer; '
                'persistence is WP-8 and screens are WP-11.',
          );
        }
      }
    });
  });

  group('colours and sizes live in design/ only', () {
    // `Colors\.` needs a left boundary. Without one it also matches inside
    // `DhaagaColors.light` — the semantic token this rule exists to push people
    // towards — so the rule fired on the two correct usages in the gallery and
    // would have fired on every future one. A rule that fails on compliance is
    // worse than no rule: it gets suppressed, and the real violations go with
    // it. The lookbehind rejects a match preceded by an identifier character,
    // so `Colors.red` is still caught wherever it appears and `AnythingColors.`
    // is not.
    final colourLiteral = RegExp(r'Color\(0x|(?<![A-Za-z0-9_$])Colors\.');

    test('no component or gallery file names a raw colour', () {
      for (final dir in <String>['lib/components', 'lib/gallery']) {
        for (final file in _dartFiles(dir)) {
          final offending = file
              .readAsStringSync()
              .split('\n')
              .asMap()
              .entries
              .where((e) =>
                  colourLiteral.hasMatch(e.value) &&
                  !e.value.trimLeft().startsWith('//'))
              .map((e) => '${file.path}:${e.key + 1}')
              .toList();
          expect(
            offending,
            isEmpty,
            reason: 'raw colour(s) at $offending. Bind to a semantic token, or '
                'the contrast test cannot see it.',
          );
        }
      }
    });
  });
}
