#!/usr/bin/env python3
"""
Dhaaga hard-coded literal scan.

Two rules, two passes, one script.

RULE 1 - no hard-coded business rule (AP-1, BR-21).
    "Any business rule a shop owner could reasonably want to change is data,
    not code." A literal threshold, rate or window in application code is a
    defect, because the owner cannot reach it and the CA sign-off cannot cover
    it. The scan looks for a numeric or quoted constant assigned to, or
    compared against, an identifier whose name reads like a business rule.

RULE 2 - no hard-coded user-visible string (WP-9).
    README has asserted this since WP-1: "No user-visible string is hard-coded;
    English in V1, Hindi architecture from P0, Urdu addable later." Nothing
    enforced it. Rule 1's pattern cannot: `Text('Save')` contains no
    rule-shaped identifier, so the scan reported clean over a lib/main.dart
    that held four hard-coded strings.

    The second pass looks for a string literal handed to a parameter that puts
    words in front of a person: a Text child, or an argument whose name ends in
    label, title, message, hint or text.

    This pass and gen-l10n's missing-key failure are two halves of one guard
    and neither is sufficient alone. gen-l10n cannot see a string that was
    never added to a catalogue; this pass cannot see a key that was added and
    left untranslated. Both run in CI.

Both passes are built to be trusted rather than believed:

  * --selftest plants known violations of BOTH rules and fails if the scan
    misses any, so a clean run means the scan works rather than that it looked
    nowhere;
  * the run reports how many files it read. Zero files scanned is a failure,
    not a pass;
  * an exception is declared in the code itself with a trailing or preceding
    "dhaaga:allow-literal <reason>" comment, so every exception is visible in
    the diff that introduces it and carries its justification.

Places where literals legitimately live are excluded by path: the configuration
registry and its shipped defaults, the seed, the test suite, and generated
localisation output.

Known limitation, stated rather than discovered later: both passes are
line-based, so a literal split across lines is not seen. Widening to a Dart
parser would catch those and would also make this script depend on the Dart
toolchain, which the database side of CI does not have. The allowance comment
and review cover the gap.

Usage:
    scan_hardcoded.py            scan and report
    scan_hardcoded.py --selftest prove the scan detects planted violations
    scan_hardcoded.py --list     list the files that would be scanned
"""

from __future__ import annotations

import argparse
import re
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Application code, wherever it lives. Dart directories are listed ahead of
# their existence: WP-8 onward writes into them and the scan must already be
# watching when it does.
SCAN_ROOTS = ["lib", "app", "packages", "db/migrations", "db/rollback", "scripts", "supabase/functions"]
SCAN_SUFFIXES = {".dart", ".sql", ".py", ".ts", ".js"}

# Literals belong here by definition.
EXCLUDE_PATHS = {
    "db/migrations/0004_configuration.sql",   # the registry and its defaults
    "db/rollback/0004_configuration.down.sql",
    "scripts/scan_hardcoded.py",              # this file names the vocabulary
}
EXCLUDE_DIRS = {"db/seed", "db/tests", "db/verify", ".git", "node_modules", "build", ".dart_tool"}

# Generated by `flutter gen-l10n` from the .arb catalogues. Every string in it
# is a catalogue entry by construction - that is the whole point of the file -
# so scanning it would report the catalogue to itself. Matched by prefix so the
# per-locale files (app_localizations_en.dart, _hi.dart) are covered too.
EXCLUDE_PREFIXES = ("lib/l10n/app_localizations",)

RULE_WORDS = (
    "rate|percent|pct|threshold|tolerance|buffer|reserve|dormanc|quota|capacity"
    "|discount|fee|markup|margin|gst|vat|cess|surcharge|commission|penalty"
    "|retention|expiry|grace|slab|cutoff|min_order|max_order|lease_size"
    "|warn_after|target_seconds|_days|_hours|_minutes"
)

# Rule 1: name <op> literal, where the name reads like a business rule.
VIOLATION = re.compile(
    r"(?ix)"
    # The rule word may begin the identifier ("dormancyDays") or sit inside it
    # ("gstRate"), so the leading run must be allowed to match nothing.
    r"\b(?P<name>[\w.]*(?:" + RULE_WORDS + r")[\w.]*)\s*"
    r"(?P<op>:=|==|=|>=|<=|>|<)\s*"
    r"(?P<value>-?\d+(?:\.\d+)?\b|'[^']{1,40}'|\"[^\"]{1,40}\")"
)

# SQL keywords that the name pattern can otherwise swallow.
KEYWORD_NAMES = {"limit", "offset", "fetch", "rate", "percent"}

# Rule 2: a string literal placed where a person will read it.
#
# Two shapes cover almost all of it in practice:
#   Text('Save')                        - the Text widget's positional child
#   labelText: 'Chest'                  - any argument that names displayed words
#
# The suffix list is deliberately broad: `fieldLabel`, `semanticsLabel`,
# `hintText`, `errorMessage` and `helperText` all put words on a screen, and a
# scan that only knew `label:` would miss most of them.
UI_TEXT_WIDGETS = "Text|SelectableText|TextSpan"
UI_ARG_SUFFIXES = "label|title|message|hint|text"

UI_STRING = re.compile(
    r"(?x)"
    r"(?:"
    r"  \b(?P<widget>" + UI_TEXT_WIDGETS + r")\s*\(\s*(?P<wvalue>'[^']*'|\"[^\"]*\")"
    r"|"
    # The suffix may BE the whole name ("label:") or sit at the end of a longer
    # one ("fieldLabel:", "hintText:"), so the leading run must be allowed to
    # match nothing. This script made the opposite mistake once before, in WP-6,
    # where a required leading character meant `dormancyDays` was never matched.
    r"  \b(?P<arg>\w*(?:" + UI_ARG_SUFFIXES + r"))\s*:\s*(?P<avalue>'[^']*'|\"[^\"]*\")"
    r")",
    re.IGNORECASE,
)

ALLOW = re.compile(r"dhaaga:allow-literal(?:\s+(?P<reason>.+))?")

# A literal that carries no business meaning on its own.
STRUCTURAL_VALUES = {"0", "1", "-1", "''", '""'}

# Dart string interpolation: "${expr}" or "$identifier.path".
INTERPOLATION = re.compile(r"\$\{[^}]*\}|\$[A-Za-z_]\w*(?:\.\w+)*")


def is_structural_ui_string(literal: str) -> bool:
    """True when a string literal carries no words of its own.

    Strip the quotes, strip every interpolation, and ask whether any letter is
    left. This is what separates

        '${l10n.reasonPromptTitle} $domain'   - composed entirely of values
        'Total: $amount'                      - a hard-coded English word

    and it matters, because flagging the first would train people to reach for
    the allowance comment out of habit, which is how an enforcement mechanism
    stops meaning anything. Empty strings, separators and bare numbers fall out
    of the same test.
    """
    body = literal[1:-1] if len(literal) >= 2 else literal
    return not any(ch.isalpha() for ch in INTERPOLATION.sub("", body))

GREEN = "\033[32m"
RED = "\033[31m"
DIM = "\033[2m"
RESET = "\033[0m"

KIND_RULE = "business rule"
KIND_UI = "user-visible string"


class Finding:
    def __init__(self, path: Path, lineno: int, name: str, value: str, line: str,
                 kind: str = KIND_RULE):
        self.path, self.lineno, self.name, self.value, self.line = path, lineno, name, value, line
        self.kind = kind

    def render(self, root: Path) -> str:
        rel = self.path.relative_to(root)
        return (f"  {rel}:{self.lineno}\n"
                f"      {self.name} = {self.value}\n"
                f"      {DIM}{self.line.strip()[:110]}{RESET}")


def is_excluded(path: Path, root: Path) -> bool:
    rel = path.relative_to(root).as_posix()
    if rel in EXCLUDE_PATHS:
        return True
    if rel.startswith(EXCLUDE_PREFIXES):
        return True
    return any(rel == d or rel.startswith(d + "/") for d in EXCLUDE_DIRS)


def discover(root: Path) -> list[Path]:
    files: list[Path] = []
    for name in SCAN_ROOTS:
        base = root / name
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_file() and path.suffix in SCAN_SUFFIXES and not is_excluded(path, root):
                files.append(path)
    return files


def _allowed(lines: list[str], index: int) -> bool:
    """An allowance sits on the line itself, or on the line above - which is how
    a multi-line declaration declares itself."""
    if ALLOW.search(lines[index - 1]):
        return True
    return index >= 2 and ALLOW.search(lines[index - 2]) is not None


def scan_file(path: Path) -> list[Finding]:
    findings: list[Finding] = []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return findings

    is_dart = path.suffix == ".dart"

    for index, line in enumerate(lines, start=1):
        if _allowed(lines, index):
            continue

        # Rule 1 - business-rule literals, every language.
        for match in VIOLATION.finditer(line):
            name = match.group("name")
            if name.lower() in KEYWORD_NAMES:
                continue
            value = match.group("value")
            if value in STRUCTURAL_VALUES:
                continue
            findings.append(Finding(path, index, name, value, line, KIND_RULE))

        # Rule 2 - user-visible strings. Dart only: this is about what a widget
        # puts on a screen, and no other language in the tree draws one.
        if not is_dart:
            continue
        for match in UI_STRING.finditer(line):
            name = match.group("widget") or match.group("arg")
            value = match.group("wvalue") or match.group("avalue")
            if is_structural_ui_string(value):
                continue
            findings.append(Finding(path, index, name, value, line, KIND_UI))

    return findings


def run(root: Path, quiet: bool = False) -> tuple[int, list[Finding]]:
    files = discover(root)
    findings: list[Finding] = []
    for path in files:
        findings.extend(scan_file(path))

    if quiet:
        return len(files), findings

    rules = [f for f in findings if f.kind == KIND_RULE]
    strings = [f for f in findings if f.kind == KIND_UI]

    print()
    print(f"hard-coded literal scan  {DIM}({len(files)} files){RESET}")
    print()

    if rules:
        print(f"{RED}business rules in code{RESET}  {DIM}(AP-1, BR-21){RESET}")
        for finding in rules:
            print(finding.render(root))
        print()
        print("        Move the value into config_setting, or declare the exception with a")
        print("        'dhaaga:allow-literal <reason>' comment on or above the line.")
        print()

    if strings:
        print(f"{RED}user-visible strings in code{RESET}  {DIM}(README: no hard-coded string){RESET}")
        for finding in strings:
            print(finding.render(root))
        print()
        print("        Move the words into lib/l10n/app_en.arb and read them through")
        print("        AppLocalizations, or - if these words belong to the shop rather than")
        print("        to the product - resolve them from the translation table and declare")
        print("        the exception with 'dhaaga:allow-literal <reason>'.")
        print()

    if findings:
        print(f"{RED}FAILED{RESET}  {len(rules)} rule-shaped literal(s), "
              f"{len(strings)} user-visible string(s)")
        print()
    elif len(files) == 0:
        print(f"{RED}FAILED{RESET}  no files scanned - a clean result would be vacuous")
        print()
    else:
        print(f"{GREEN}PASSED{RESET}  no rule-shaped literals and no hard-coded "
              f"user-visible strings in {len(files)} files")
        print()

    return len(files), findings


def selftest() -> int:
    """A clean scan is only evidence if the scan can fail."""
    print()
    print("scan self-test")
    print()
    passed = failed = 0

    def check(name: str, condition: bool, detail: str = "") -> None:
        nonlocal passed, failed
        if condition:
            passed += 1
            print(f"{GREEN}ok{RESET}    {name}")
        else:
            failed += 1
            print(f"{RED}FAIL{RESET}  {name}\n      {detail}")

    with tempfile.TemporaryDirectory() as tmp:
        fake = Path(tmp)
        (fake / "lib").mkdir()

        # --- rule 1: business-rule literals ---------------------------------
        planted = fake / "lib" / "pricing.dart"
        planted.write_text(
            "class Pricing {\n"
            "  static const double gstRate = 18.0;\n"
            "  static const int dormancyDays = 270;\n"
            "  int lineCount = 1;\n"
            "  // dhaaga:allow-literal the schema itself fixes two decimal places\n"
            "  static const int moneyScale = 2;\n"
            "  static const double reworkReservePercent = 12.0; // dhaaga:allow-literal deliberate\n"
            "}\n",
            encoding="utf-8",
        )

        # --- rule 2: user-visible strings ------------------------------------
        widget = fake / "lib" / "counter.dart"
        widget.write_text(
            "Widget build(BuildContext context) {\n"
            "  return Column(children: [\n"
            "    const Text('Save'),\n"
            "    Text(l10n.stateEmpty),\n"
            "    TextField(labelText: 'Chest'),\n"
            "    TextField(hintText: 'Enter a number'),\n"
            "    Semantics(semanticsLabel: 'Balance due'),\n"
            # A BARE suffix, not a prefixed one. The pattern missed this shape
            # until the first real scan found it; it stays planted so it cannot
            # be reintroduced by a future tightening of the regex.
            "    Chip(label: 'Cancelled'),\n"
            # Composed entirely of catalogue values - not a violation.
            "    Semantics(label: '${l10n.reasonPromptTitle} $domain'),\n"
            # Interpolation does not launder a hard-coded English word.
            "    Text('Total: $amount'),\n"
            "    const Text(''),\n"
            "    const Text('-'),\n"
            "    // dhaaga:allow-literal the shop owns this word, not the product\n"
            "    TextField(fieldLabel: 'Sleeve'),\n"
            "  ]);\n"
            "}\n",
            encoding="utf-8",
        )

        count, findings = run(fake, quiet=True)
        rules = sorted(f.name for f in findings if f.kind == KIND_RULE)
        strings = sorted(f.value for f in findings if f.kind == KIND_UI)

        check("the scan reads planted files", count == 2, f"scanned {count}")

        # Rule 1 - unchanged behaviour, still proven.
        check("a hard-coded tax rate is found", "gstRate" in rules, str(rules))
        check("a hard-coded dormancy window is found", "dormancyDays" in rules, str(rules))
        check("a structural literal is not reported", "lineCount" not in rules, str(rules))
        check("an allowance on the line above is honoured", "moneyScale" not in rules, str(rules))
        check("an allowance on the line itself is honoured",
              "reworkReservePercent" not in rules, str(rules))
        check("no business rule is reported beyond the two planted",
              len(rules) == 2, str(rules))

        # Rule 2 - the guard WP-9 adds.
        check("a hard-coded Text() string is found", "'Save'" in strings, str(strings))
        check("a hard-coded labelText is found", "'Chest'" in strings, str(strings))
        check("a hard-coded hintText is found", "'Enter a number'" in strings, str(strings))
        check("a hard-coded semanticsLabel is found", "'Balance due'" in strings, str(strings))
        check("a hard-coded BARE label: is found", "'Cancelled'" in strings, str(strings))
        check("a string composed only of interpolated values is not reported",
              not any('reasonPromptTitle' in v for v in strings), str(strings))
        check("interpolation does not launder a hard-coded word",
              any(v.startswith("'Total:") for v in strings), str(strings))
        check("a catalogue lookup is not reported", "l10n.stateEmpty" not in str(strings),
              str(strings))
        check("an empty string is not reported", "''" not in strings, str(strings))
        check("a bare symbol is not reported", "'-'" not in strings, str(strings))
        check("an allowance covers a tenant-owned label", "'Sleeve'" not in strings, str(strings))
        check("no user-visible string is reported beyond the six planted",
              len(strings) == 6, str(strings))

        # A .dart-only rule must not start firing on SQL or Python.
        (fake / "scripts").mkdir()
        (fake / "scripts" / "thing.py").write_text(
            "label = 'not a widget'\nprint('hello')\n", encoding="utf-8")
        _, mixed = run(fake, quiet=True)
        py_strings = [f for f in mixed
                      if f.kind == KIND_UI and f.path.suffix == ".py"]
        check("the user-visible-string rule does not fire outside Dart",
              len(py_strings) == 0, str([f.value for f in py_strings]))

        empty = Path(tmp) / "empty"
        empty.mkdir()
        zero_count, _ = run(empty, quiet=True)
        check("an empty tree scans zero files, which the run treats as a failure", zero_count == 0)

    print()
    if failed:
        print(f"{RED}FAILED{RESET}  {passed} passed, {failed} failed")
        print()
        return 1
    print(f"{GREEN}PASSED{RESET}  {passed} checks")
    print()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Dhaaga hard-coded literal scan")
    parser.add_argument("--selftest", action="store_true", help="prove the scan detects planted violations")
    parser.add_argument("--list", action="store_true", help="list the files that would be scanned")
    args = parser.parse_args()

    if args.selftest:
        return selftest()

    if args.list:
        for path in discover(REPO_ROOT):
            print(path.relative_to(REPO_ROOT))
        return 0

    count, findings = run(REPO_ROOT)
    return 1 if (findings or count == 0) else 0


if __name__ == "__main__":
    raise SystemExit(main())
